Controllers/GamesController.cs
using GameZone.Models;
using GameZone.Services;
using GameZone.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Security.Cryptography;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace GameZone.Controllers
{
    //[Authorize(Roles = ClsRoles.roleUser)]
    public class GamesController : Controller
    {
        public GamesController(AppDbContext context,
            ICategoriesService categories,
            IDevicesService devicesService,
            IGamesService gamesService)
        {
            _context = context;
            _categoriesService = categories;
            _devicesService = devicesService;
            _gamesService = gamesService;
        }
        private readonly IGamesService _gamesService;
        private readonly ICategoriesService _categoriesService;
        private readonly IDevicesService _devicesService;
        private readonly AppDbContext _context;
        public IActionResult Index()
        {
            var games = _gamesService.GetAll();
            return View(games);
        }
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            var game = _gamesService.GetById(id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }


        [HttpGet]
        public IActionResult Create()
        {
            CreateGameFormViewModel viewModel = new()
            {
                Select_Categories = _categoriesService.GetCategories(),
                Select_Devices = _devicesService.GetDevices(),
            };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGameFormViewModel mdl)
        {
            CreateGameFormViewModel viewModel = new()
            {
                Select_Categories = _categoriesService.GetCategories(),
                Select_Devices = _devicesService.GetDevices(),
            };

            if (!ModelState.IsValid)
            {
                mdl.Select_Categories = _categoriesService.GetCategories();
                mdl.Select_Devices = _devicesService.GetDevices();
                return View(viewModel);
            }
            await _gamesService.Create(mdl);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var game = _gamesService.GetById(id);

            if (game is null)
                return NotFound();

            EditGameFormViewModel viewModel = new()
            {
                Id = id,
                Name = game.Name,
                Description = game.Description,
                categoryId = game.categoryId,
                SelectedDevices = game.gameDevices.Select(d => d.deviceId).ToList(),
                Select_Categories = _categoriesService.GetCategories(),
                Select_Devices = _devicesService.GetDevices(),
                CurrentCover = game.Cover
            };

            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditGameFormViewModel model)
        {
            
            if (!ModelState.IsValid)
            {
                model.Select_Categories = _categoriesService.GetCategories();
                model.Select_Devices = _devicesService.GetDevices();
                TempData["Error"] = "Oops!!";
                return View(model);
            }

            var game = await _gamesService.Update(model);
            TempData["Success"] = "your game has been edited";
            return RedirectToAction(nameof(Index));
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var isDeleted = _gamesService.Delete(id);

            return isDeleted ? Ok() : BadRequest();
        }
       
    }
}

Controllers/RolesController.cs
using GameZone.Settings;
using GameZone.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GameZone.Controllers
{
    [Authorize(Roles = ClsRoles.roleAdmin)]
    public class RolesController : Controller
    {
        public RolesController(UserManager<IdentityUser> user, RoleManager<IdentityRole> roles)
        {
            _user = user;
            _roles = roles;
        }

        private readonly UserManager<IdentityUser> _user;
        private readonly RoleManager<IdentityRole> _roles;

        public async Task<IActionResult> Index()
        {
            var _users = await _user.Users.ToListAsync();
            return View(_users);
        }

        public async Task<IActionResult> addRoles(string userId)
        {
            var user = await _user.FindByIdAsync(userId);
            var userRoles = await _user.GetRolesAsync(user);

            var allRoles = await _roles.Roles.ToListAsync();
            if (allRoles != null)
            {
                var roleList = allRoles.Select(r => new RoleViewModel()
                {
                    roleId = r.Id,
                    roleName = r.Name,
                    useRole = userRoles.Any(x => x == r.Name)
                });
                ViewBag.userName = user.UserName;
                ViewBag.userId = userId;
                return View(roleList);
            }
            else
                return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> addRoles(string userId, string jsonRoles)
        {
            var user = await _user.FindByIdAsync(userId);

            List<RoleViewModel> myRoles =
                JsonConvert.DeserializeObject<List<RoleViewModel>>(jsonRoles);

            if (user != null)
            {
                var userRoles = await _user.GetRolesAsync(user);

                foreach (var role in myRoles)
                {
                    if (userRoles.Any(x => x == role.roleName.Trim()) && !role.useRole)
                    {
                        await _user.RemoveFromRoleAsync(user, role.roleName.Trim());
                    }

                    if (!userRoles.Any(x => x == role.roleName.Trim()) && role.useRole)
                    {
                        await _user.AddToRoleAsync(user, role.roleName.Trim());
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            else
                return NotFound();
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GameZone | @ViewData["Title"] </title>
    
    <link rel="icon" href="~/arrow.ico" type="image/x-icon" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameZone.styles.css" asp-append-version="true" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light mb-3" data-bs-theme="light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameZone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            var user = await UserManager.GetUserAsync(User);
                            if (await UserManager.IsInRoleAsync(user, ClsRoles.roleAdmin))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Games" asp-action="Index">My Games</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Roles" asp-action="Index">Roles</a>
                                </li>
                            }
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="CountriesAndCities">Counties</a>
                        </li>
                     </ul>
                    <div>
                       
                    </div>

                    <form asp-controller="Home" asp-action="Index" class="d-flex" method="get">
                        <input name="seachName" class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                               value="@ViewBag.seachName">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>


                   
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GameZone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#page').DataTable();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["Success"]
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["Error"]
    </div>
}